--- 
title: "本硕博学位论文模板"
subtitle: "中国矿业大学（北京）"
author: "黄湘云"
date: "`r format(Sys.time(), tz = 'Asia/Taipei', usetz = TRUE)`"
site: bookdown::bookdown_site
geometry: margin=1.18in
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: gbt7714-unsrt
natbiboptions: super,square
lof: no
lot: no
graphics: yes
tables: yes
link-citations: yes
links-as-notes: yes
colorlinks: yes
mathspec: yes
toccolor: magenta
classoption: "hyperref, a4paper, UTF8, zihao = -4, linespread = 1.3, table"
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# 前言

封面、扉页、独创性声明、授权页、中英文摘要、目录、正文、参考文献、致谢、作者简介、附录

安装 TinyTeX

```{r eval=FALSE}
if (!require("tinytex")) {
  install.packages("tinytex")
} else {
  tinytex::install_tinytex(dir = "where/you/want/to/go")
}
```

安装参考文献样式和字体包

```{r eval=FALSE}
tinytex::tlmgr_install(pkgs = c(
  "ctex", "xecjk", "zhnumber", "fandol",
  "unicode-math", "filehook", "lm-math",
  "gbt7714", "sourcecodepro",
  "sourceserifpro", "sourcesanspro"
))
```

解释一下 `classoption` 的内容

```ymal
classoption: "hyperref, a4paper, UTF8, zihao = -4, linespread = 1.3, table"
```

Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r}
library(reticulate)
os <- import("os")
os$listdir(".")
```


```{python, eval = TRUE, fig.cap = "公式", dev = if (knitr::is_latex_output()) "pdf" else "png"}
from __future__ import unicode_literals
import numpy as np
import matplotlib
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['text.latex.unicode'] = True
import matplotlib.pyplot as plt
plt.switch_backend('agg') # Very Important in R Markdown

t = np.linspace(0.0, 1.0, 100)
s = np.cos(4 * np.pi * t) + 2

fig, ax = plt.subplots(figsize=(6, 4), tight_layout=True)
ax.plot(t, s)

ax.set_xlabel(r'\textbf{time (s)}')
# ax.set_ylabel(r'\textit{Velocity}(\N{DEGREE SIGN}/sec)', fontsize=16)
ax.set_ylabel(r'\textit{Velocity}($^{\circ}$/sec)', fontsize=16)
ax.set_title(r'\TeX\ is Number $\displaystyle\sum_{n=1}^\infty'
             r'\frac{-e^{i\pi}}{2^n}$!', fontsize=16, color='r')
plt.show()
#plt.savefig('test.svg') 
```



```{r include=FALSE,cache=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
